update_files
Manel0712/05_JavaScript_functions pull request #1
Opened 2023-11-14 19:23 UTC by Manel0712

2023-11-19 20:10 UTC, tictools requested changes

2023-11-19 20:10 UTC, tictools commented on exercise_02/getTotalWordsFromString.js
> +  const numberWords = sentence.split(/\s+/);
Do you know what does `/\s+/` mean? Which type of expression is it? 🤔

2023-11-19 20:10 UTC, tictools commented on exercise_05/isAdditionGreaterThanFifty.js
> +const isAdditionGreaterThanFifty = function (summand1, summand2) {
You can simplify this logic, as far as `summand1 + summand2 >= 50` is directly returning a boolean

2023-11-19 20:10 UTC, tictools commented on exercise_06/checkCollectionHasElements.js
YouYou can simplify this logic, as far as `collection.length > 0` is directly returning a boolean

2023-11-19 20:10 UTC, tictools commented on exercise_07/isTypeOf.js
> +function isTypeOf(value, type) {
This logic can be simplified, avoid using `switch` if you can use simpler structures with `if`.

2023-11-20 18:40 UTC, aalvar0 approved these changes
I don't see any errors to fix.

2023-11-21 06:27 UTC, tictools approved these changes

2023-11-21 06:41 UTC, merged